### ISSUE TITLE
  IndexError: list index out of range

### ISSUE THREAD

**Issue by mubasharrazakz** [abhilampard/Simple-Plagiarism-Checker#1]
when i enter text in box on browser and hit enter the following error is showing on cmd.
 dotProduct += queryTF[i]*databaseTF[i]
IndexError: list index out of range.

**Comment by abhilampard** [comment]
> when i enter text in box on browser and hit enter the following error is showing on cmd.
> dotProduct += queryTF[i]*databaseTF[i]
> IndexError: list index out of range.

Hey there,
Are you using the same database file that I put up? I don't have the setup with me right now to try out things since I am using a new laptop. But I am pretty sure this code worked out as it is.

**Comment by mubasharrazakz** [comment]
Yes it is same file, provided on GitHuB.
Please check the files attached.
